server:
  port: 8761

spring:
  application:
    name: pampas-registry-server

eureka:
  datacenter: default
  environment: test
  instance:
    leaseRenewalIntervalInSeconds: 30
  client:
    registryFetchIntervalSeconds: 30
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  security:
    enabled: false