server:
  port: 7777

spring:
  application:
    name: pampas-resource-server

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
  client:
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  security:
    enabled: false

security:
  oauth2:
    resource:
      token-info-uri: ${AUTH_SERVICE_URL:http://localhost:9999/authz}/oauth/check_token
    client:
      client-id: demo
      client-secret: demo

logging:
  level:
    org.springframework.security: DEBUG
