server:
  port: 8080

spring:
  application:
    name: pampas-ui-server

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
  client:
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: ${AUTH_SERVICE_URL:http://localhost:9999/authz}/oauth/token
      user-authorization-uri: ${AUTH_SERVICE_URL:http://localhost:9999/authz}/oauth/authorize
      scope: read, write
    resource:
      token-info-uri: ${AUTH_SERVICE_URL:http://localhost:9999/authz}/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG



