server:
  port: 9000

spring:
  application:
    name: pampas-admin-server

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
  client:
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  security:
    enabled: false